
ACTION LocalArrayAction: 

	localArray1[0] := localArray.0;
	localArray1[1] := localArray.1;
	localArray1[2] := localArray.2;
	localArray1[3] := localArray.3;
	localArray1[4] := localArray.4;
	localArray1[5] := localArray.5;
	localArray1[6] := localArray.6;
	localArray1[7] := localArray.7;
	localArray1[8] := localArray.8;
	localArray1[9] := localArray.9;
	localArray1[10] := localArray.10;
	localArray1[11] := localArray.11;
	localArray1[12] := localArray.12;
	localArray1[13] := localArray.13;
	localArray1[14] := localArray.14;
	localArray1[15] := localArray.15;
	
END_ACTION
